http://localhost:8080/flats

###

http://localhost:8080/flats/1

###

http://localhost:8080/flats/owners/1

###

http://localhost:8080/flats/1/save?ownerId=1&district=Московский&price=3&rooms=2

###

http://localhost:8080/flats/1/save?ownerId=2&district=Приволжский&price=3&rooms=2

###

http://localhost:8080/flats/3/remove