http://localhost:8080/products

###

http://localhost:8080/products/1

###

http://localhost:8080/products/worker/1

###

http://localhost:8080/products/1/save?workerId=1&items=Молоко&price=50&quantity=20

###

http://localhost:8080/products/1/save?workerId=2&items=Хлеб&price=30&quantity=50

###

http://localhost:8080/products/3/remove